

baseURL = "http://blogg.rosbacke.org/"
paginate = 6
title = "Software development musings"
dateFormat = "2006-01-02"
theme = "hugo-theme-casper"
#theme = "hugo_theme_aglaus"

# pygmentsStyle = "manni"
# pygmentsStyle = "native"
pygmentsStyle = "monokai"
# pygmentsUseClasses = true

pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClassic = true

[params]
  author = "Mikael Rosbacke"
  description = "Welcome to my website"
  githubName = "rosbacke"
  GitHubUser = "rosbacke"
  languageCode = "en-us"
  cover = "images/IMG_0200.JPG"
  logo = "images/Mikael2.jpg"
  enableRobotsTXT = true

[permalinks]
  post = "/:year/:month/:title/"

[frontmatter]
date = ["date","publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date","publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[blackfriday]
  angledQuotes = true
  extensions = ["hardLineBreak"]
  fractions = false
  plainIDAnchors = true

[[menu.main]]
  name = "Home"
  weight = -100
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
